import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'gu';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    languageCode: 'en',
    diagnosisLabel: 'Diagnosis',
    adviceLabel: 'Advice',
    confidenceLabel: 'Confidence',
    appName: 'Krishi-Mitra',
    tagline: 'Smart Farmer Empowerment',
    welcome: 'Your trusted companion for smart farming decisions',
    dashboard: 'Dashboard',
    advisory: 'Farm Advisory',
    market: 'Market Linkage',
    diagnosis: 'Crop Diagnosis',
    contact: 'Contact',
    signOut: 'Sign Out',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    location: 'Location',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    checkEmail: 'Please check your email for verification link',
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    features: 'Features',
    aiAdvisory: 'AI-Powered Farm Advisory',
    aiAdvisoryDesc: 'Get personalized farming advice using advanced AI',
    marketLinkage: 'Direct Market Linkage',
    marketLinkageDesc: 'Connect directly with buyers and sellers',
    cropDiagnosis: 'Crop Disease Diagnosis',
    cropDiagnosisDesc: 'Diagnose crop diseases using AI image analysis',
    weatherInfo: 'Weather Information',
    weatherInfoDesc: 'Real-time weather updates for your location',
    advisoryHistory: 'Advisory History',
    addListing: 'Add Listing',
    crop: 'Crop',
    quantity: 'Quantity',
    unit: 'Unit',
    price: 'Price',
    save: 'Save',
    cancel: 'Cancel',
    getAdvice: 'Get Advice',
    season: 'Season',
    uploadImage: 'Upload Crop Image',
    submit: 'Submit',
    diagnosing: 'Diagnosing...',
    contactUs: 'Contact Us',
    contactName: 'Name',
    contactMessage: 'Message',
    send: 'Send',
    dateLabel: 'Date',
    temperatureLabel: 'Temperature',
    humidityLabel: 'Humidity',
    weatherLabel: 'Weather',
    searchCity: 'Enter city name',
    edit: 'Edit',
    delete: 'Delete',
    update: 'Update',
    loading: 'Loading...',
    search: 'Search',
    feelsLikeLabel: 'Feels Like',
    windLabel: 'Wind',
    foggy: 'Foggy',
  },
  hi: {
    languageCode: 'hi',
    diagnosisLabel: 'निदान',
    adviceLabel: 'सलाह',
    confidenceLabel: 'विश्वास',
    appName: 'कृषि-मित्र',
    tagline: 'स्मार्ट किसान सशक्तिकरण',
    welcome: 'स्मार्ट खेती के फैसलों के लिए आपका विश्वसनीय साथी',
    dashboard: 'डैशबोर्ड',
    advisory: 'कृषि सलाह',
    market: 'बाजार लिंकेज',
    diagnosis: 'फसल निदान',
    contact: 'संपर्क',
    signOut: 'साइन आउट',
    signIn: 'साइन इन',
    signUp: 'साइन अप',
    email: 'ईमेल',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    fullName: 'पूरा नाम',
    location: 'स्थान',
    alreadyHaveAccount: 'क्या आपके पास पहले से एक खाता मौजूद है?',
    dontHaveAccount: 'क्या आपके पास खाता नहीं है?',
    checkEmail: 'कृपया सत्यापन लिंक के लिए अपना ईमेल जांचें',
    getStarted: 'शुरू करें',
    learnMore: 'और जानें',
    features: 'विशेषताएं',
    aiAdvisory: 'AI-संचालित कृषि सलाह',
    aiAdvisoryDesc: 'उन्नत AI का उपयोग करके व्यक्तिगत खेती की सलाह प्राप्त करें',
    marketLinkage: 'प्रत्यक्ष बाजार लिंकेज',
    marketLinkageDesc: 'खरीदारों और विक्रेताओं से सीधे जुड़ें',
    cropDiagnosis: 'फसल रोग निदान',
    cropDiagnosisDesc: 'AI छवि विश्लेषण का उपयोग करके फसल रोगों का निदान करें',
    weatherInfo: 'मौसम की जानकारी',
    weatherInfoDesc: 'आपके स्थान के लिए वास्तविक समय मौसम अपडेट',
    advisoryHistory: 'सलाह इतिहास',
    addListing: 'लिस्टिंग जोड़ें',
    crop: 'फसल',
    quantity: 'मात्रा',
    unit: 'इकाई',
    price: 'कीमत',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    getAdvice: 'सलाह प्राप्त करें',
    season: 'मौसम',
    uploadImage: 'फसल की छवि अपलोड करें',
    submit: 'जमा करें',
    diagnosing: 'निदान हो रहा है...',
    contactUs: 'हमसे संपर्क करें',
    contactName: 'नाम',
    contactMessage: 'संदेश',
    send: 'भेजें',
    dateLabel: 'तारीख',
    temperatureLabel: 'तापमान',
    humidityLabel: 'आर्द्रता',
    weatherLabel: 'मौसम',
    searchCity: 'शहर का नाम दर्ज करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    update: 'अपडेट करें',
    loading: 'लोड हो रहा है...',
    search: 'खोज',
    feelsLikeLabel: 'महसूस होता है',
    windLabel: 'हवा',
    foggy: 'कोहरा',
  },
  gu: {
    languageCode: 'gu',
    diagnosisLabel: 'નિદાન',
    adviceLabel: 'સલાહ',
    confidenceLabel: 'વિશ્વાસ',
    appName: 'કૃષિ-મિત્ર',
    tagline: 'સ્માર્ટ ખેડૂત સશક્તિકરણ',
    welcome: 'સ્માર્ટ ખેતીના નિર્ણયો માટે તમારો વિશ્વસનીય સાથી',
    dashboard: 'ડેશબોર્ડ',
    advisory: 'ખેતી સલાહ',
    market: 'બજાર લિંકેજ',
    diagnosis: 'પાક નિદાન',
    contact: 'સંપર્ક',
    signOut: 'સાઇન આઉટ',
    signIn: 'સાઇન ઇન',
    signUp: 'સાઇન અપ',
    email: 'ઇમેઇલ',
    password: 'પાસવર્ડ',
    confirmPassword: 'પાસવર્ડની પુષ્ટિ કરો',
    fullName: 'પૂરું નામ',
    location: 'સ્થાન',
    alreadyHaveAccount: 'શું તમારી પાસે પહેલેથી ખાતું છે?',
    dontHaveAccount: 'શું તમારી પાસે ખાતું નથી?',
    checkEmail: 'કૃપા કરીને ચકાસણી લિંક માટે તમારો ઇમેઇલ તપાસો',
    getStarted: 'પ્રારંભ કરો',
    learnMore: 'વધુ જાણો',
    features: 'લક્ષણો',
    aiAdvisory: 'AI-સંચાલિત ખેતી સલાહ',
    aiAdvisoryDesc: 'અદ્યતન AI નો ઉપયોગ કરીને વ્યક્તિગત ખેતીની સલાહ મેળવો',
    marketLinkage: 'સીધું બજાર લિંકેજ',
    marketLinkageDesc: 'ખરીદદારો અને વેચાણકર્તાઓ સાથે સીધા જોડાઓ',
    cropDiagnosis: 'પાક રોગ નિદાન',
    cropDiagnosisDesc: 'AI છબી વિશ્લેષણનો ઉપયોગ કરીને પાક રોગોનું નિદાન કરો',
    weatherInfo: 'હવામાન માહિતી',
    weatherInfoDesc: 'તમારા સ્થાન માટે રીઅલ-ટાઇમ હવામાન અપડેટ્સ',
    advisoryHistory: 'સલાહ ઇતિહાસ',
    addListing: 'લિસ્ટિંગ ઉમેરો',
    crop: 'પાક',
    quantity: 'જથ્થો',
    unit: 'એકમ',
    price: 'કિંમત',
    save: 'સાચવો',
    cancel: 'રદ કરો',
    getAdvice: 'સલાહ મેળવો',
    season: 'મોસમ',
    uploadImage: 'પાકની છબી અપલોડ કરો',
    submit: 'સબમિટ કરો',
    diagnosing: 'નિદાન થઈ રહ્યું છે...',
    contactUs: 'અમારો સંપર્ક કરો',
    contactName: 'નામ',
    contactMessage: 'સંદેશ',
    send: 'મોકલો',
    dateLabel: 'તારીખ',
    temperatureLabel: 'તાપમાન',
    humidityLabel: 'ભેજ',
    weatherLabel: 'હવામાન',
    searchCity: 'શહેરનું નામ દાખલ કરો',
    edit: 'સંપાદિત કરો',
    delete: 'કાઢી નાખો',
    update: 'અપડેટ કરો',
    loading: 'લોડ કરી રહ્યું છે...',
    search: 'શોધો',
    feelsLikeLabel: 'અનુભવાય છે',
    windLabel: 'પવન',
    foggy: 'ધુમ્મસ',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const translation = translations[language] as { [key: string]: string };
    return translation[key] || translations.en[key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
